/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the hookhq SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx endpointGroupsDelete.example.ts
 */

import { HookHQ } from "hookhq";

const hookHQ = new HookHQ({
  serverURL: "https://api.example.com",
  security: {
    bearerAuth: process.env["HOOKHQ_BEARER_AUTH"] ?? "",
  },
});

async function main() {
  await hookHQ.endpointGroups.delete({
    id: "grp_a1b2_efgh5678",
  });
}

main().catch(console.error);
