/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteEventTypesIdRequest = {
  /**
   * Event type ID
   */
  id: string;
};

/** @internal */
export const DeleteEventTypesIdRequest$inboundSchema: z.ZodType<
  DeleteEventTypesIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteEventTypesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteEventTypesIdRequest$outboundSchema: z.ZodType<
  DeleteEventTypesIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteEventTypesIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteEventTypesIdRequest$ {
  /** @deprecated use `DeleteEventTypesIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteEventTypesIdRequest$inboundSchema;
  /** @deprecated use `DeleteEventTypesIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteEventTypesIdRequest$outboundSchema;
  /** @deprecated use `DeleteEventTypesIdRequest$Outbound` instead. */
  export type Outbound = DeleteEventTypesIdRequest$Outbound;
}

export function deleteEventTypesIdRequestToJSON(
  deleteEventTypesIdRequest: DeleteEventTypesIdRequest,
): string {
  return JSON.stringify(
    DeleteEventTypesIdRequest$outboundSchema.parse(deleteEventTypesIdRequest),
  );
}

export function deleteEventTypesIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEventTypesIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEventTypesIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEventTypesIdRequest' from JSON`,
  );
}
