/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteEndpointsIdRequest = {
  /**
   * Endpoint ID
   */
  id: string;
};

/** @internal */
export const DeleteEndpointsIdRequest$inboundSchema: z.ZodType<
  DeleteEndpointsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteEndpointsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteEndpointsIdRequest$outboundSchema: z.ZodType<
  DeleteEndpointsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteEndpointsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteEndpointsIdRequest$ {
  /** @deprecated use `DeleteEndpointsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteEndpointsIdRequest$inboundSchema;
  /** @deprecated use `DeleteEndpointsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteEndpointsIdRequest$outboundSchema;
  /** @deprecated use `DeleteEndpointsIdRequest$Outbound` instead. */
  export type Outbound = DeleteEndpointsIdRequest$Outbound;
}

export function deleteEndpointsIdRequestToJSON(
  deleteEndpointsIdRequest: DeleteEndpointsIdRequest,
): string {
  return JSON.stringify(
    DeleteEndpointsIdRequest$outboundSchema.parse(deleteEndpointsIdRequest),
  );
}

export function deleteEndpointsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEndpointsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEndpointsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEndpointsIdRequest' from JSON`,
  );
}
