/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetEndpointsRequest = {
  /**
   * Whether to filter endpoints by enabled status
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const GetEndpointsRequest$inboundSchema: z.ZodType<
  GetEndpointsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean().optional(),
});

/** @internal */
export type GetEndpointsRequest$Outbound = {
  enabled?: boolean | undefined;
};

/** @internal */
export const GetEndpointsRequest$outboundSchema: z.ZodType<
  GetEndpointsRequest$Outbound,
  z.ZodTypeDef,
  GetEndpointsRequest
> = z.object({
  enabled: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetEndpointsRequest$ {
  /** @deprecated use `GetEndpointsRequest$inboundSchema` instead. */
  export const inboundSchema = GetEndpointsRequest$inboundSchema;
  /** @deprecated use `GetEndpointsRequest$outboundSchema` instead. */
  export const outboundSchema = GetEndpointsRequest$outboundSchema;
  /** @deprecated use `GetEndpointsRequest$Outbound` instead. */
  export type Outbound = GetEndpointsRequest$Outbound;
}

export function getEndpointsRequestToJSON(
  getEndpointsRequest: GetEndpointsRequest,
): string {
  return JSON.stringify(
    GetEndpointsRequest$outboundSchema.parse(getEndpointsRequest),
  );
}

export function getEndpointsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetEndpointsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEndpointsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEndpointsRequest' from JSON`,
  );
}
