/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchEndpointsIdRequest = {
  /**
   * Endpoint ID
   */
  id: string;
};

/** @internal */
export const PatchEndpointsIdRequest$inboundSchema: z.ZodType<
  PatchEndpointsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PatchEndpointsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PatchEndpointsIdRequest$outboundSchema: z.ZodType<
  PatchEndpointsIdRequest$Outbound,
  z.ZodTypeDef,
  PatchEndpointsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchEndpointsIdRequest$ {
  /** @deprecated use `PatchEndpointsIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchEndpointsIdRequest$inboundSchema;
  /** @deprecated use `PatchEndpointsIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchEndpointsIdRequest$outboundSchema;
  /** @deprecated use `PatchEndpointsIdRequest$Outbound` instead. */
  export type Outbound = PatchEndpointsIdRequest$Outbound;
}

export function patchEndpointsIdRequestToJSON(
  patchEndpointsIdRequest: PatchEndpointsIdRequest,
): string {
  return JSON.stringify(
    PatchEndpointsIdRequest$outboundSchema.parse(patchEndpointsIdRequest),
  );
}

export function patchEndpointsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchEndpointsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchEndpointsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchEndpointsIdRequest' from JSON`,
  );
}
