/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchEndpointGroupsIdRequest = {
  /**
   * Endpoint group ID
   */
  id: string;
};

/** @internal */
export const PatchEndpointGroupsIdRequest$inboundSchema: z.ZodType<
  PatchEndpointGroupsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PatchEndpointGroupsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PatchEndpointGroupsIdRequest$outboundSchema: z.ZodType<
  PatchEndpointGroupsIdRequest$Outbound,
  z.ZodTypeDef,
  PatchEndpointGroupsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchEndpointGroupsIdRequest$ {
  /** @deprecated use `PatchEndpointGroupsIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchEndpointGroupsIdRequest$inboundSchema;
  /** @deprecated use `PatchEndpointGroupsIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchEndpointGroupsIdRequest$outboundSchema;
  /** @deprecated use `PatchEndpointGroupsIdRequest$Outbound` instead. */
  export type Outbound = PatchEndpointGroupsIdRequest$Outbound;
}

export function patchEndpointGroupsIdRequestToJSON(
  patchEndpointGroupsIdRequest: PatchEndpointGroupsIdRequest,
): string {
  return JSON.stringify(
    PatchEndpointGroupsIdRequest$outboundSchema.parse(
      patchEndpointGroupsIdRequest,
    ),
  );
}

export function patchEndpointGroupsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchEndpointGroupsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchEndpointGroupsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchEndpointGroupsIdRequest' from JSON`,
  );
}
