/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Event type schema
 */
export type PatchEventTypesIdSchema = {};

export type PatchEventTypesIdRequestBody = {
  /**
   * Event type name
   */
  name?: string | undefined;
  /**
   * Event type description
   */
  description?: string | undefined;
  /**
   * Event type schema
   */
  schema?: PatchEventTypesIdSchema | undefined;
  /**
   * Event type enabled status
   */
  enabled?: boolean | undefined;
};

export type PatchEventTypesIdRequest = {
  /**
   * Event type ID
   */
  id: string;
  requestBody: PatchEventTypesIdRequestBody;
};

/** @internal */
export const PatchEventTypesIdSchema$inboundSchema: z.ZodType<
  PatchEventTypesIdSchema,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PatchEventTypesIdSchema$Outbound = {};

/** @internal */
export const PatchEventTypesIdSchema$outboundSchema: z.ZodType<
  PatchEventTypesIdSchema$Outbound,
  z.ZodTypeDef,
  PatchEventTypesIdSchema
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchEventTypesIdSchema$ {
  /** @deprecated use `PatchEventTypesIdSchema$inboundSchema` instead. */
  export const inboundSchema = PatchEventTypesIdSchema$inboundSchema;
  /** @deprecated use `PatchEventTypesIdSchema$outboundSchema` instead. */
  export const outboundSchema = PatchEventTypesIdSchema$outboundSchema;
  /** @deprecated use `PatchEventTypesIdSchema$Outbound` instead. */
  export type Outbound = PatchEventTypesIdSchema$Outbound;
}

export function patchEventTypesIdSchemaToJSON(
  patchEventTypesIdSchema: PatchEventTypesIdSchema,
): string {
  return JSON.stringify(
    PatchEventTypesIdSchema$outboundSchema.parse(patchEventTypesIdSchema),
  );
}

export function patchEventTypesIdSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PatchEventTypesIdSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchEventTypesIdSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchEventTypesIdSchema' from JSON`,
  );
}

/** @internal */
export const PatchEventTypesIdRequestBody$inboundSchema: z.ZodType<
  PatchEventTypesIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  schema: z.lazy(() => PatchEventTypesIdSchema$inboundSchema).optional(),
  enabled: z.boolean().optional(),
});

/** @internal */
export type PatchEventTypesIdRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  schema?: PatchEventTypesIdSchema$Outbound | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const PatchEventTypesIdRequestBody$outboundSchema: z.ZodType<
  PatchEventTypesIdRequestBody$Outbound,
  z.ZodTypeDef,
  PatchEventTypesIdRequestBody
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  schema: z.lazy(() => PatchEventTypesIdSchema$outboundSchema).optional(),
  enabled: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchEventTypesIdRequestBody$ {
  /** @deprecated use `PatchEventTypesIdRequestBody$inboundSchema` instead. */
  export const inboundSchema = PatchEventTypesIdRequestBody$inboundSchema;
  /** @deprecated use `PatchEventTypesIdRequestBody$outboundSchema` instead. */
  export const outboundSchema = PatchEventTypesIdRequestBody$outboundSchema;
  /** @deprecated use `PatchEventTypesIdRequestBody$Outbound` instead. */
  export type Outbound = PatchEventTypesIdRequestBody$Outbound;
}

export function patchEventTypesIdRequestBodyToJSON(
  patchEventTypesIdRequestBody: PatchEventTypesIdRequestBody,
): string {
  return JSON.stringify(
    PatchEventTypesIdRequestBody$outboundSchema.parse(
      patchEventTypesIdRequestBody,
    ),
  );
}

export function patchEventTypesIdRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PatchEventTypesIdRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchEventTypesIdRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchEventTypesIdRequestBody' from JSON`,
  );
}

/** @internal */
export const PatchEventTypesIdRequest$inboundSchema: z.ZodType<
  PatchEventTypesIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => PatchEventTypesIdRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchEventTypesIdRequest$Outbound = {
  id: string;
  RequestBody: PatchEventTypesIdRequestBody$Outbound;
};

/** @internal */
export const PatchEventTypesIdRequest$outboundSchema: z.ZodType<
  PatchEventTypesIdRequest$Outbound,
  z.ZodTypeDef,
  PatchEventTypesIdRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => PatchEventTypesIdRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchEventTypesIdRequest$ {
  /** @deprecated use `PatchEventTypesIdRequest$inboundSchema` instead. */
  export const inboundSchema = PatchEventTypesIdRequest$inboundSchema;
  /** @deprecated use `PatchEventTypesIdRequest$outboundSchema` instead. */
  export const outboundSchema = PatchEventTypesIdRequest$outboundSchema;
  /** @deprecated use `PatchEventTypesIdRequest$Outbound` instead. */
  export type Outbound = PatchEventTypesIdRequest$Outbound;
}

export function patchEventTypesIdRequestToJSON(
  patchEventTypesIdRequest: PatchEventTypesIdRequest,
): string {
  return JSON.stringify(
    PatchEventTypesIdRequest$outboundSchema.parse(patchEventTypesIdRequest),
  );
}

export function patchEventTypesIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchEventTypesIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchEventTypesIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchEventTypesIdRequest' from JSON`,
  );
}
