/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Payload to send with the webhook
 */
export type PayloadRequest = {};

export type PostWebhooksSendRequestBody = {
  /**
   * List of endpoints or endpoint groups to send the webhook to
   */
  endpoints: Array<string>;
  /**
   * Event type to send the webhook to. Required if sending to an endpoint group.
   */
  eventType?: string | undefined;
  /**
   * Payload to send with the webhook
   */
  payload: PayloadRequest;
  /**
   * Optional unique event ID to track the webhook
   */
  eventId?: string | undefined;
};

export type PostWebhooksSendRequest = {
  /**
   * Optional idempotency key
   */
  idempotencyKey?: string | undefined;
  requestBody?: PostWebhooksSendRequestBody | undefined;
};

/**
 * Payload
 */
export type PayloadResponse = {};

/**
 * Webhook sent
 */
export type PostWebhooksSendResponse = {
  /**
   * Webhook ID
   */
  id?: string | undefined;
  /**
   * Event ID
   */
  eventId?: string | undefined;
  /**
   * Event type
   */
  eventType?: string | undefined;
  /**
   * Payload
   */
  payload?: PayloadResponse | undefined;
  /**
   * Channels the webhook was sent to
   */
  channels?: Array<string> | undefined;
  /**
   * Timestamp the webhook was sent
   */
  timestamp?: string | undefined;
};

/** @internal */
export const PayloadRequest$inboundSchema: z.ZodType<
  PayloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PayloadRequest$Outbound = {};

/** @internal */
export const PayloadRequest$outboundSchema: z.ZodType<
  PayloadRequest$Outbound,
  z.ZodTypeDef,
  PayloadRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayloadRequest$ {
  /** @deprecated use `PayloadRequest$inboundSchema` instead. */
  export const inboundSchema = PayloadRequest$inboundSchema;
  /** @deprecated use `PayloadRequest$outboundSchema` instead. */
  export const outboundSchema = PayloadRequest$outboundSchema;
  /** @deprecated use `PayloadRequest$Outbound` instead. */
  export type Outbound = PayloadRequest$Outbound;
}

export function payloadRequestToJSON(payloadRequest: PayloadRequest): string {
  return JSON.stringify(PayloadRequest$outboundSchema.parse(payloadRequest));
}

export function payloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<PayloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayloadRequest' from JSON`,
  );
}

/** @internal */
export const PostWebhooksSendRequestBody$inboundSchema: z.ZodType<
  PostWebhooksSendRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  endpoints: z.array(z.string()),
  eventType: z.string().optional(),
  payload: z.lazy(() => PayloadRequest$inboundSchema),
  eventId: z.string().optional(),
});

/** @internal */
export type PostWebhooksSendRequestBody$Outbound = {
  endpoints: Array<string>;
  eventType?: string | undefined;
  payload: PayloadRequest$Outbound;
  eventId?: string | undefined;
};

/** @internal */
export const PostWebhooksSendRequestBody$outboundSchema: z.ZodType<
  PostWebhooksSendRequestBody$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendRequestBody
> = z.object({
  endpoints: z.array(z.string()),
  eventType: z.string().optional(),
  payload: z.lazy(() => PayloadRequest$outboundSchema),
  eventId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendRequestBody$ {
  /** @deprecated use `PostWebhooksSendRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendRequestBody$inboundSchema;
  /** @deprecated use `PostWebhooksSendRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostWebhooksSendRequestBody$outboundSchema;
  /** @deprecated use `PostWebhooksSendRequestBody$Outbound` instead. */
  export type Outbound = PostWebhooksSendRequestBody$Outbound;
}

export function postWebhooksSendRequestBodyToJSON(
  postWebhooksSendRequestBody: PostWebhooksSendRequestBody,
): string {
  return JSON.stringify(
    PostWebhooksSendRequestBody$outboundSchema.parse(
      postWebhooksSendRequestBody,
    ),
  );
}

export function postWebhooksSendRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostWebhooksSendRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostWebhooksSendRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostWebhooksSendRequestBody' from JSON`,
  );
}

/** @internal */
export const PostWebhooksSendRequest$inboundSchema: z.ZodType<
  PostWebhooksSendRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Idempotency-Key": z.string().optional(),
  RequestBody: z.lazy(() => PostWebhooksSendRequestBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Idempotency-Key": "idempotencyKey",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PostWebhooksSendRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  RequestBody?: PostWebhooksSendRequestBody$Outbound | undefined;
};

/** @internal */
export const PostWebhooksSendRequest$outboundSchema: z.ZodType<
  PostWebhooksSendRequest$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  requestBody: z.lazy(() => PostWebhooksSendRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "Idempotency-Key",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendRequest$ {
  /** @deprecated use `PostWebhooksSendRequest$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendRequest$inboundSchema;
  /** @deprecated use `PostWebhooksSendRequest$outboundSchema` instead. */
  export const outboundSchema = PostWebhooksSendRequest$outboundSchema;
  /** @deprecated use `PostWebhooksSendRequest$Outbound` instead. */
  export type Outbound = PostWebhooksSendRequest$Outbound;
}

export function postWebhooksSendRequestToJSON(
  postWebhooksSendRequest: PostWebhooksSendRequest,
): string {
  return JSON.stringify(
    PostWebhooksSendRequest$outboundSchema.parse(postWebhooksSendRequest),
  );
}

export function postWebhooksSendRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostWebhooksSendRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostWebhooksSendRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostWebhooksSendRequest' from JSON`,
  );
}

/** @internal */
export const PayloadResponse$inboundSchema: z.ZodType<
  PayloadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PayloadResponse$Outbound = {};

/** @internal */
export const PayloadResponse$outboundSchema: z.ZodType<
  PayloadResponse$Outbound,
  z.ZodTypeDef,
  PayloadResponse
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayloadResponse$ {
  /** @deprecated use `PayloadResponse$inboundSchema` instead. */
  export const inboundSchema = PayloadResponse$inboundSchema;
  /** @deprecated use `PayloadResponse$outboundSchema` instead. */
  export const outboundSchema = PayloadResponse$outboundSchema;
  /** @deprecated use `PayloadResponse$Outbound` instead. */
  export type Outbound = PayloadResponse$Outbound;
}

export function payloadResponseToJSON(
  payloadResponse: PayloadResponse,
): string {
  return JSON.stringify(PayloadResponse$outboundSchema.parse(payloadResponse));
}

export function payloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayloadResponse' from JSON`,
  );
}

/** @internal */
export const PostWebhooksSendResponse$inboundSchema: z.ZodType<
  PostWebhooksSendResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  eventId: z.string().optional(),
  eventType: z.string().optional(),
  payload: z.lazy(() => PayloadResponse$inboundSchema).optional(),
  channels: z.array(z.string()).optional(),
  timestamp: z.string().optional(),
});

/** @internal */
export type PostWebhooksSendResponse$Outbound = {
  id?: string | undefined;
  eventId?: string | undefined;
  eventType?: string | undefined;
  payload?: PayloadResponse$Outbound | undefined;
  channels?: Array<string> | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const PostWebhooksSendResponse$outboundSchema: z.ZodType<
  PostWebhooksSendResponse$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendResponse
> = z.object({
  id: z.string().optional(),
  eventId: z.string().optional(),
  eventType: z.string().optional(),
  payload: z.lazy(() => PayloadResponse$outboundSchema).optional(),
  channels: z.array(z.string()).optional(),
  timestamp: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendResponse$ {
  /** @deprecated use `PostWebhooksSendResponse$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendResponse$inboundSchema;
  /** @deprecated use `PostWebhooksSendResponse$outboundSchema` instead. */
  export const outboundSchema = PostWebhooksSendResponse$outboundSchema;
  /** @deprecated use `PostWebhooksSendResponse$Outbound` instead. */
  export type Outbound = PostWebhooksSendResponse$Outbound;
}

export function postWebhooksSendResponseToJSON(
  postWebhooksSendResponse: PostWebhooksSendResponse,
): string {
  return JSON.stringify(
    PostWebhooksSendResponse$outboundSchema.parse(postWebhooksSendResponse),
  );
}

export function postWebhooksSendResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostWebhooksSendResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostWebhooksSendResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostWebhooksSendResponse' from JSON`,
  );
}
