/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Retry policy of the endpoint
 */
export const RetryPolicy = {
  Exponential: "exponential",
  Linear: "linear",
  Fixed: "fixed",
} as const;
/**
 * Retry policy of the endpoint
 */
export type RetryPolicy = ClosedEnum<typeof RetryPolicy>;

/**
 * Custom headers of the endpoint
 */
export type CustomHeaders = {};

export type PostEndpointsRequest = {
  /**
   * Name of the endpoint
   */
  name: string;
  /**
   * Description of the endpoint
   */
  description?: string | undefined;
  /**
   * URL of the endpoint
   */
  url: string;
  /**
   * Whether the endpoint is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Retry policy of the endpoint
   */
  retryPolicy?: RetryPolicy | undefined;
  /**
   * Maximum number of attempts of the endpoint
   */
  maxAttempts?: number | undefined;
  /**
   * Timeout of the endpoint
   */
  timeoutMs?: number | undefined;
  /**
   * Custom headers of the endpoint
   */
  customHeaders?: CustomHeaders | undefined;
  /**
   * Proxy group ID of the endpoint
   */
  proxyGroupId?: string | undefined;
};

/** @internal */
export const RetryPolicy$inboundSchema: z.ZodNativeEnum<typeof RetryPolicy> = z
  .nativeEnum(RetryPolicy);

/** @internal */
export const RetryPolicy$outboundSchema: z.ZodNativeEnum<typeof RetryPolicy> =
  RetryPolicy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetryPolicy$ {
  /** @deprecated use `RetryPolicy$inboundSchema` instead. */
  export const inboundSchema = RetryPolicy$inboundSchema;
  /** @deprecated use `RetryPolicy$outboundSchema` instead. */
  export const outboundSchema = RetryPolicy$outboundSchema;
}

/** @internal */
export const CustomHeaders$inboundSchema: z.ZodType<
  CustomHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CustomHeaders$Outbound = {};

/** @internal */
export const CustomHeaders$outboundSchema: z.ZodType<
  CustomHeaders$Outbound,
  z.ZodTypeDef,
  CustomHeaders
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomHeaders$ {
  /** @deprecated use `CustomHeaders$inboundSchema` instead. */
  export const inboundSchema = CustomHeaders$inboundSchema;
  /** @deprecated use `CustomHeaders$outboundSchema` instead. */
  export const outboundSchema = CustomHeaders$outboundSchema;
  /** @deprecated use `CustomHeaders$Outbound` instead. */
  export type Outbound = CustomHeaders$Outbound;
}

export function customHeadersToJSON(customHeaders: CustomHeaders): string {
  return JSON.stringify(CustomHeaders$outboundSchema.parse(customHeaders));
}

export function customHeadersFromJSON(
  jsonString: string,
): SafeParseResult<CustomHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomHeaders' from JSON`,
  );
}

/** @internal */
export const PostEndpointsRequest$inboundSchema: z.ZodType<
  PostEndpointsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  url: z.string(),
  enabled: z.boolean().default(true),
  retryPolicy: RetryPolicy$inboundSchema.default("exponential"),
  maxAttempts: z.number().default(3),
  timeoutMs: z.number().default(30000),
  customHeaders: z.lazy(() => CustomHeaders$inboundSchema).optional(),
  proxyGroupId: z.string().optional(),
});

/** @internal */
export type PostEndpointsRequest$Outbound = {
  name: string;
  description?: string | undefined;
  url: string;
  enabled: boolean;
  retryPolicy: string;
  maxAttempts: number;
  timeoutMs: number;
  customHeaders?: CustomHeaders$Outbound | undefined;
  proxyGroupId?: string | undefined;
};

/** @internal */
export const PostEndpointsRequest$outboundSchema: z.ZodType<
  PostEndpointsRequest$Outbound,
  z.ZodTypeDef,
  PostEndpointsRequest
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  url: z.string(),
  enabled: z.boolean().default(true),
  retryPolicy: RetryPolicy$outboundSchema.default("exponential"),
  maxAttempts: z.number().default(3),
  timeoutMs: z.number().default(30000),
  customHeaders: z.lazy(() => CustomHeaders$outboundSchema).optional(),
  proxyGroupId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostEndpointsRequest$ {
  /** @deprecated use `PostEndpointsRequest$inboundSchema` instead. */
  export const inboundSchema = PostEndpointsRequest$inboundSchema;
  /** @deprecated use `PostEndpointsRequest$outboundSchema` instead. */
  export const outboundSchema = PostEndpointsRequest$outboundSchema;
  /** @deprecated use `PostEndpointsRequest$Outbound` instead. */
  export type Outbound = PostEndpointsRequest$Outbound;
}

export function postEndpointsRequestToJSON(
  postEndpointsRequest: PostEndpointsRequest,
): string {
  return JSON.stringify(
    PostEndpointsRequest$outboundSchema.parse(postEndpointsRequest),
  );
}

export function postEndpointsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostEndpointsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostEndpointsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostEndpointsRequest' from JSON`,
  );
}
