/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * JSON Schema for event payload validation (must be valid JSON Schema)
 */
export type PostEventTypesSchema = {};

export type PostEventTypesRequest = {
  /**
   * Name of the event type
   */
  name: string;
  /**
   * Description of the event type
   */
  description?: string | undefined;
  /**
   * JSON Schema for event payload validation (must be valid JSON Schema)
   */
  schema?: PostEventTypesSchema | undefined;
  /**
   * Whether the event type is enabled
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const PostEventTypesSchema$inboundSchema: z.ZodType<
  PostEventTypesSchema,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PostEventTypesSchema$Outbound = {};

/** @internal */
export const PostEventTypesSchema$outboundSchema: z.ZodType<
  PostEventTypesSchema$Outbound,
  z.ZodTypeDef,
  PostEventTypesSchema
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostEventTypesSchema$ {
  /** @deprecated use `PostEventTypesSchema$inboundSchema` instead. */
  export const inboundSchema = PostEventTypesSchema$inboundSchema;
  /** @deprecated use `PostEventTypesSchema$outboundSchema` instead. */
  export const outboundSchema = PostEventTypesSchema$outboundSchema;
  /** @deprecated use `PostEventTypesSchema$Outbound` instead. */
  export type Outbound = PostEventTypesSchema$Outbound;
}

export function postEventTypesSchemaToJSON(
  postEventTypesSchema: PostEventTypesSchema,
): string {
  return JSON.stringify(
    PostEventTypesSchema$outboundSchema.parse(postEventTypesSchema),
  );
}

export function postEventTypesSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PostEventTypesSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostEventTypesSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostEventTypesSchema' from JSON`,
  );
}

/** @internal */
export const PostEventTypesRequest$inboundSchema: z.ZodType<
  PostEventTypesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.lazy(() => PostEventTypesSchema$inboundSchema).optional(),
  enabled: z.boolean().optional(),
});

/** @internal */
export type PostEventTypesRequest$Outbound = {
  name: string;
  description?: string | undefined;
  schema?: PostEventTypesSchema$Outbound | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const PostEventTypesRequest$outboundSchema: z.ZodType<
  PostEventTypesRequest$Outbound,
  z.ZodTypeDef,
  PostEventTypesRequest
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.lazy(() => PostEventTypesSchema$outboundSchema).optional(),
  enabled: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostEventTypesRequest$ {
  /** @deprecated use `PostEventTypesRequest$inboundSchema` instead. */
  export const inboundSchema = PostEventTypesRequest$inboundSchema;
  /** @deprecated use `PostEventTypesRequest$outboundSchema` instead. */
  export const outboundSchema = PostEventTypesRequest$outboundSchema;
  /** @deprecated use `PostEventTypesRequest$Outbound` instead. */
  export type Outbound = PostEventTypesRequest$Outbound;
}

export function postEventTypesRequestToJSON(
  postEventTypesRequest: PostEventTypesRequest,
): string {
  return JSON.stringify(
    PostEventTypesRequest$outboundSchema.parse(postEventTypesRequest),
  );
}

export function postEventTypesRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostEventTypesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostEventTypesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostEventTypesRequest' from JSON`,
  );
}
