/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiPortalTokenRequest = {
  /**
   * ID of the endpoint group to manage
   */
  endpointGroupId: string;
  /**
   * List of event types the user can subscribe to
   */
  allowedEventTypes?: Array<string> | undefined;
  /**
   * Name of the application for the back button
   */
  applicationName?: string | undefined;
  /**
   * URL to return to when user clicks back button
   */
  returnUrl?: string | undefined;
};

/**
 * Endpoint group information
 */
export type EndpointGroup = {
  /**
   * Endpoint group ID
   */
  id?: string | undefined;
  /**
   * Endpoint group name
   */
  name?: string | undefined;
  /**
   * Environment ID
   */
  environmentId?: string | undefined;
};

/**
 * JWT token generated successfully
 */
export type PostApiPortalTokenResponse = {
  /**
   * JWT token for portal access
   */
  token?: string | undefined;
  /**
   * URL to the portal with token
   */
  portalUrl?: string | undefined;
  /**
   * Token expiration time in seconds
   */
  expiresIn?: number | undefined;
  /**
   * Endpoint group information
   */
  endpointGroup?: EndpointGroup | undefined;
};

/** @internal */
export const PostApiPortalTokenRequest$inboundSchema: z.ZodType<
  PostApiPortalTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  endpointGroupId: z.string(),
  allowedEventTypes: z.array(z.string()).optional(),
  applicationName: z.string().optional(),
  returnUrl: z.string().optional(),
});

/** @internal */
export type PostApiPortalTokenRequest$Outbound = {
  endpointGroupId: string;
  allowedEventTypes?: Array<string> | undefined;
  applicationName?: string | undefined;
  returnUrl?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenRequest$outboundSchema: z.ZodType<
  PostApiPortalTokenRequest$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenRequest
> = z.object({
  endpointGroupId: z.string(),
  allowedEventTypes: z.array(z.string()).optional(),
  applicationName: z.string().optional(),
  returnUrl: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenRequest$ {
  /** @deprecated use `PostApiPortalTokenRequest$inboundSchema` instead. */
  export const inboundSchema = PostApiPortalTokenRequest$inboundSchema;
  /** @deprecated use `PostApiPortalTokenRequest$outboundSchema` instead. */
  export const outboundSchema = PostApiPortalTokenRequest$outboundSchema;
  /** @deprecated use `PostApiPortalTokenRequest$Outbound` instead. */
  export type Outbound = PostApiPortalTokenRequest$Outbound;
}

export function postApiPortalTokenRequestToJSON(
  postApiPortalTokenRequest: PostApiPortalTokenRequest,
): string {
  return JSON.stringify(
    PostApiPortalTokenRequest$outboundSchema.parse(postApiPortalTokenRequest),
  );
}

export function postApiPortalTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPortalTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPortalTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPortalTokenRequest' from JSON`,
  );
}

/** @internal */
export const EndpointGroup$inboundSchema: z.ZodType<
  EndpointGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  environmentId: z.string().optional(),
});

/** @internal */
export type EndpointGroup$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  environmentId?: string | undefined;
};

/** @internal */
export const EndpointGroup$outboundSchema: z.ZodType<
  EndpointGroup$Outbound,
  z.ZodTypeDef,
  EndpointGroup
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  environmentId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EndpointGroup$ {
  /** @deprecated use `EndpointGroup$inboundSchema` instead. */
  export const inboundSchema = EndpointGroup$inboundSchema;
  /** @deprecated use `EndpointGroup$outboundSchema` instead. */
  export const outboundSchema = EndpointGroup$outboundSchema;
  /** @deprecated use `EndpointGroup$Outbound` instead. */
  export type Outbound = EndpointGroup$Outbound;
}

export function endpointGroupToJSON(endpointGroup: EndpointGroup): string {
  return JSON.stringify(EndpointGroup$outboundSchema.parse(endpointGroup));
}

export function endpointGroupFromJSON(
  jsonString: string,
): SafeParseResult<EndpointGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EndpointGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EndpointGroup' from JSON`,
  );
}

/** @internal */
export const PostApiPortalTokenResponse$inboundSchema: z.ZodType<
  PostApiPortalTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
  portalUrl: z.string().optional(),
  expiresIn: z.number().optional(),
  endpointGroup: z.lazy(() => EndpointGroup$inboundSchema).optional(),
});

/** @internal */
export type PostApiPortalTokenResponse$Outbound = {
  token?: string | undefined;
  portalUrl?: string | undefined;
  expiresIn?: number | undefined;
  endpointGroup?: EndpointGroup$Outbound | undefined;
};

/** @internal */
export const PostApiPortalTokenResponse$outboundSchema: z.ZodType<
  PostApiPortalTokenResponse$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenResponse
> = z.object({
  token: z.string().optional(),
  portalUrl: z.string().optional(),
  expiresIn: z.number().optional(),
  endpointGroup: z.lazy(() => EndpointGroup$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenResponse$ {
  /** @deprecated use `PostApiPortalTokenResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiPortalTokenResponse$inboundSchema;
  /** @deprecated use `PostApiPortalTokenResponse$outboundSchema` instead. */
  export const outboundSchema = PostApiPortalTokenResponse$outboundSchema;
  /** @deprecated use `PostApiPortalTokenResponse$Outbound` instead. */
  export type Outbound = PostApiPortalTokenResponse$Outbound;
}

export function postApiPortalTokenResponseToJSON(
  postApiPortalTokenResponse: PostApiPortalTokenResponse,
): string {
  return JSON.stringify(
    PostApiPortalTokenResponse$outboundSchema.parse(postApiPortalTokenResponse),
  );
}

export function postApiPortalTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPortalTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPortalTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPortalTokenResponse' from JSON`,
  );
}
