/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostEndpointGroupsRequest = {
  /**
   * Name of the endpoint group
   */
  name: string;
  /**
   * Description of the endpoint group
   */
  description?: string | undefined;
  /**
   * List of endpoint IDs
   */
  endpointIds?: Array<string> | undefined;
  /**
   * Whether the endpoint group is enabled
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const PostEndpointGroupsRequest$inboundSchema: z.ZodType<
  PostEndpointGroupsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  endpointIds: z.array(z.string()).optional(),
  enabled: z.boolean().optional(),
});

/** @internal */
export type PostEndpointGroupsRequest$Outbound = {
  name: string;
  description?: string | undefined;
  endpointIds?: Array<string> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const PostEndpointGroupsRequest$outboundSchema: z.ZodType<
  PostEndpointGroupsRequest$Outbound,
  z.ZodTypeDef,
  PostEndpointGroupsRequest
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  endpointIds: z.array(z.string()).optional(),
  enabled: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostEndpointGroupsRequest$ {
  /** @deprecated use `PostEndpointGroupsRequest$inboundSchema` instead. */
  export const inboundSchema = PostEndpointGroupsRequest$inboundSchema;
  /** @deprecated use `PostEndpointGroupsRequest$outboundSchema` instead. */
  export const outboundSchema = PostEndpointGroupsRequest$outboundSchema;
  /** @deprecated use `PostEndpointGroupsRequest$Outbound` instead. */
  export type Outbound = PostEndpointGroupsRequest$Outbound;
}

export function postEndpointGroupsRequestToJSON(
  postEndpointGroupsRequest: PostEndpointGroupsRequest,
): string {
  return JSON.stringify(
    PostEndpointGroupsRequest$outboundSchema.parse(postEndpointGroupsRequest),
  );
}

export function postEndpointGroupsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostEndpointGroupsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostEndpointGroupsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostEndpointGroupsRequest' from JSON`,
  );
}
