/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointGroupsCreate } from "../funcs/endpointGroupsCreate.js";
import { endpointGroupsDelete } from "../funcs/endpointGroupsDelete.js";
import { endpointGroupsList } from "../funcs/endpointGroupsList.js";
import { endpointGroupsUpdate } from "../funcs/endpointGroupsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EndpointGroups extends ClientSDK {
  /**
   * Delete an endpoint group
   */
  async delete(
    request: operations.DeleteEndpointGroupsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointGroupsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an endpoint group
   */
  async update(
    request: operations.PatchEndpointGroupsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointGroupsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * List endpoint groups for the current environment
   */
  async list(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointGroupsList(
      this,
      options,
    ));
  }

  /**
   * Create new endpoint group
   */
  async create(
    request?: operations.PostEndpointGroupsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointGroupsCreate(
      this,
      request,
      options,
    ));
  }
}
