/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsCreate } from "../funcs/endpointsCreate.js";
import { endpointsDelete } from "../funcs/endpointsDelete.js";
import { endpointsList } from "../funcs/endpointsList.js";
import { endpointsUpdate } from "../funcs/endpointsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Endpoints extends ClientSDK {
  /**
   * Delete an endpoint
   */
  async delete(
    request: operations.DeleteEndpointsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an endpoint
   */
  async update(
    request: operations.PatchEndpointsIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * List endpoints for the current environment
   */
  async list(
    request?: operations.GetEndpointsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create new endpoint
   */
  async create(
    request?: operations.PostEndpointsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(endpointsCreate(
      this,
      request,
      options,
    ));
  }
}
