/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesCreate } from "../funcs/eventTypesCreate.js";
import { eventTypesDelete } from "../funcs/eventTypesDelete.js";
import { eventTypesList } from "../funcs/eventTypesList.js";
import { eventTypesUpdate } from "../funcs/eventTypesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EventTypes extends ClientSDK {
  /**
   * Delete an event type
   */
  async delete(
    request: operations.DeleteEventTypesIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventTypesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an event type
   */
  async update(
    request: operations.PatchEventTypesIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventTypesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * List event types for the current environment
   */
  async list(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventTypesList(
      this,
      options,
    ));
  }

  /**
   * Create new event type
   */
  async create(
    request?: operations.PostEventTypesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventTypesCreate(
      this,
      request,
      options,
    ));
  }
}
