/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalCreate } from "../funcs/portalCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Portal extends ClientSDK {
  /**
   * Generate a JWT token for end user portal access
   */
  async create(
    request?: operations.PostApiPortalTokenRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostApiPortalTokenResponse> {
    return unwrapAsync(portalCreate(
      this,
      request,
      options,
    ));
  }
}
