/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { EndpointGroups } from "./endpointgroups.js";
import { Endpoints } from "./endpoints.js";
import { EventTypes } from "./eventtypes.js";
import { Portal } from "./portal.js";
import { Webhooks } from "./webhooks.js";

export class HookHQ extends ClientSDK {
  private _endpointGroups?: EndpointGroups;
  get endpointGroups(): EndpointGroups {
    return (this._endpointGroups ??= new EndpointGroups(this._options));
  }

  private _endpoints?: Endpoints;
  get endpoints(): Endpoints {
    return (this._endpoints ??= new Endpoints(this._options));
  }

  private _eventTypes?: EventTypes;
  get eventTypes(): EventTypes {
    return (this._eventTypes ??= new EventTypes(this._options));
  }

  private _portal?: Portal;
  get portal(): Portal {
    return (this._portal ??= new Portal(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }
}
