/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksSend } from "../funcs/webhooksSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Send a webhook to the specified endpoints.
   *
   *  Webhooks can be sent to endpoints and/or endpoint groups.
   *  In order to send a webhook to an endpoint group, the eventType must be specified, then the webhook will be dispatched to all endpoints in the group that are subscribed to the eventType.
   */
  async send(
    request?: operations.PostWebhooksSendRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostWebhooksSendResponse> {
    return unwrapAsync(webhooksSend(
      this,
      request,
      options,
    ));
  }
}
