<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


/** CustomHeaders - Custom headers of the endpoint */
class CustomHeaders
{

    public function __construct()
    {
    }
}