<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;

use Nuovar\HookHQ\Utils\SpeakeasyMetadata;
class GetEndpointsRequest
{
    /**
     * Whether to filter endpoints by enabled status
     *
     * @var ?bool $enabled
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=enabled')]
    public ?bool $enabled = null;

    /**
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(?bool $enabled = null)
    {
        $this->enabled = $enabled;
    }
}