<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


class PatchEventTypesIdRequestBody
{
    /**
     * Event type name
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Event type description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Event type schema
     *
     * @var ?PatchEventTypesIdSchema $schema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schema')]
    #[\Speakeasy\Serializer\Annotation\Type('\Nuovar\HookHQ\Models\Operations\PatchEventTypesIdSchema|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchEventTypesIdSchema $schema = null;

    /**
     * Event type enabled status
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  ?PatchEventTypesIdSchema  $schema
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $description = null, ?PatchEventTypesIdSchema $schema = null, ?bool $enabled = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->schema = $schema;
        $this->enabled = $enabled;
    }
}