<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


/** PatchEventTypesIdSchema - Event type schema */
class PatchEventTypesIdSchema
{

    public function __construct()
    {
    }
}