<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;

use Nuovar\HookHQ\Utils\SpeakeasyMetadata;
class PatchEventTypesIdRequest
{
    /**
     * Event type ID
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var PatchEventTypesIdRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PatchEventTypesIdRequestBody $requestBody;

    /**
     * @param  string  $id
     * @param  PatchEventTypesIdRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, PatchEventTypesIdRequestBody $requestBody)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}