<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


/** Payload - Payload to send with the webhook */
class Payload
{

    public function __construct()
    {
    }
}