<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


/** PostEventTypesSchema - JSON Schema for event payload validation (must be valid JSON Schema) */
class PostEventTypesSchema
{

    public function __construct()
    {
    }
}