<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


class PostEndpointGroupsRequest
{
    /**
     * Name of the endpoint group
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Description of the endpoint group
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * List of endpoint IDs
     *
     * @var ?array<string> $endpointIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endpointIds')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $endpointIds = null;

    /**
     * Whether the endpoint group is enabled
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * @param  string  $name
     * @param  ?string  $description
     * @param  ?array<string>  $endpointIds
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(string $name, ?string $description = null, ?array $endpointIds = null, ?bool $enabled = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->endpointIds = $endpointIds;
        $this->enabled = $enabled;
    }
}