<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;

use Nuovar\HookHQ\Utils\SpeakeasyMetadata;
class PostWebhooksSendRequest
{
    /**
     * Optional idempotency key
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public ?string $idempotencyKey = null;

    /**
     *
     * @var ?PostWebhooksSendRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PostWebhooksSendRequestBody $requestBody = null;

    /**
     * @param  ?string  $idempotencyKey
     * @param  ?PostWebhooksSendRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(?string $idempotencyKey = null, ?PostWebhooksSendRequestBody $requestBody = null)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->requestBody = $requestBody;
    }
}