<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


class PostEndpointsRequest
{
    /**
     * Name of the endpoint
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * URL of the endpoint
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Description of the endpoint
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Custom headers of the endpoint
     *
     * @var ?CustomHeaders $customHeaders
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customHeaders')]
    #[\Speakeasy\Serializer\Annotation\Type('\Nuovar\HookHQ\Models\Operations\CustomHeaders|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomHeaders $customHeaders = null;

    /**
     * Proxy group ID of the endpoint
     *
     * @var ?string $proxyGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('proxyGroupId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $proxyGroupId = null;

    /**
     * Whether the endpoint is enabled
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * Retry policy of the endpoint
     *
     * @var ?RetryPolicy $retryPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('retryPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Nuovar\HookHQ\Models\Operations\RetryPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RetryPolicy $retryPolicy = null;

    /**
     * Maximum number of attempts of the endpoint
     *
     * @var ?float $maxAttempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxAttempts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $maxAttempts = null;

    /**
     * Timeout of the endpoint
     *
     * @var ?float $timeoutMs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeoutMs')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $timeoutMs = null;

    /**
     * @param  string  $name
     * @param  string  $url
     * @param  ?string  $description
     * @param  ?bool  $enabled
     * @param  ?RetryPolicy  $retryPolicy
     * @param  ?float  $maxAttempts
     * @param  ?float  $timeoutMs
     * @param  ?CustomHeaders  $customHeaders
     * @param  ?string  $proxyGroupId
     * @phpstan-pure
     */
    public function __construct(string $name, string $url, ?string $description = null, ?CustomHeaders $customHeaders = null, ?string $proxyGroupId = null, ?bool $enabled = true, ?RetryPolicy $retryPolicy = RetryPolicy::Exponential, ?float $maxAttempts = 3, ?float $timeoutMs = 30000)
    {
        $this->name = $name;
        $this->url = $url;
        $this->description = $description;
        $this->customHeaders = $customHeaders;
        $this->proxyGroupId = $proxyGroupId;
        $this->enabled = $enabled;
        $this->retryPolicy = $retryPolicy;
        $this->maxAttempts = $maxAttempts;
        $this->timeoutMs = $timeoutMs;
    }
}