<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


class PostEventTypesRequest
{
    /**
     * Name of the event type
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Description of the event type
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * JSON Schema for event payload validation (must be valid JSON Schema)
     *
     * @var ?PostEventTypesSchema $schema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schema')]
    #[\Speakeasy\Serializer\Annotation\Type('\Nuovar\HookHQ\Models\Operations\PostEventTypesSchema|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostEventTypesSchema $schema = null;

    /**
     * Whether the event type is enabled
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * @param  string  $name
     * @param  ?string  $description
     * @param  ?PostEventTypesSchema  $schema
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(string $name, ?string $description = null, ?PostEventTypesSchema $schema = null, ?bool $enabled = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->schema = $schema;
        $this->enabled = $enabled;
    }
}