<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


class PostWebhooksSendRequestBody
{
    /**
     * List of endpoints or endpoint groups to send the webhook to
     *
     * @var array<string> $endpoints
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endpoints')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $endpoints;

    /**
     * Payload to send with the webhook
     *
     * @var Payload $payload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payload')]
    #[\Speakeasy\Serializer\Annotation\Type('\Nuovar\HookHQ\Models\Operations\Payload')]
    public Payload $payload;

    /**
     * Event type to send the webhook to. Required if sending to an endpoint group.
     *
     * @var ?string $eventType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $eventType = null;

    /**
     * Optional unique event ID to track the webhook
     *
     * @var ?string $eventId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $eventId = null;

    /**
     * @param  array<string>  $endpoints
     * @param  Payload  $payload
     * @param  ?string  $eventType
     * @param  ?string  $eventId
     * @phpstan-pure
     */
    public function __construct(array $endpoints, Payload $payload, ?string $eventType = null, ?string $eventId = null)
    {
        $this->endpoints = $endpoints;
        $this->payload = $payload;
        $this->eventType = $eventType;
        $this->eventId = $eventId;
    }
}