<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Operations;


/** Retry policy of the endpoint */
enum RetryPolicy: string
{
    case Exponential = 'exponential';
    case Linear = 'linear';
    case Fixed = 'fixed';
}
