<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Nuovar\HookHQ\Models\Components;

use Nuovar\HookHQ\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var ?string $bearerAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $bearerAuth = null;

    /**
     *
     * @var ?string $apiKeyCookie
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=cookie,name=apiKeyCookie')]
    public ?string $apiKeyCookie = null;

    /**
     * @param  ?string  $bearerAuth
     * @param  ?string  $apiKeyCookie
     * @phpstan-pure
     */
    public function __construct(?string $bearerAuth = null, ?string $apiKeyCookie = null)
    {
        $this->bearerAuth = $bearerAuth;
        $this->apiKeyCookie = $apiKeyCookie;
    }
}