"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .delete_endpoint_groups_id_op import (
        DeleteEndpointGroupsIDRequest,
        DeleteEndpointGroupsIDRequestTypedDict,
    )
    from .delete_endpoints_id_op import (
        DeleteEndpointsIDRequest,
        DeleteEndpointsIDRequestTypedDict,
    )
    from .delete_event_types_id_op import (
        DeleteEventTypesIDRequest,
        DeleteEventTypesIDRequestTypedDict,
    )
    from .get_endpointsop import GetEndpointsRequest, GetEndpointsRequestTypedDict
    from .patch_endpoint_groups_id_op import (
        PatchEndpointGroupsIDRequest,
        PatchEndpointGroupsIDRequestTypedDict,
    )
    from .patch_endpoints_id_op import (
        PatchEndpointsIDRequest,
        PatchEndpointsIDRequestTypedDict,
    )
    from .patch_event_types_id_op import (
        PatchEventTypesIDRequest,
        PatchEventTypesIDRequestBody,
        PatchEventTypesIDRequestBodyTypedDict,
        PatchEventTypesIDRequestTypedDict,
        PatchEventTypesIDSchema,
        PatchEventTypesIDSchemaTypedDict,
    )
    from .post_endpoint_groupsop import (
        PostEndpointGroupsRequest,
        PostEndpointGroupsRequestTypedDict,
    )
    from .post_endpointsop import (
        CustomHeaders,
        CustomHeadersTypedDict,
        PostEndpointsRequest,
        PostEndpointsRequestTypedDict,
        RetryPolicy,
    )
    from .post_event_typesop import (
        PostEventTypesRequest,
        PostEventTypesRequestTypedDict,
        PostEventTypesSchema,
        PostEventTypesSchemaTypedDict,
    )
    from .post_webhooks_sendop import (
        Payload,
        PayloadTypedDict,
        PostWebhooksSendRequest,
        PostWebhooksSendRequestBody,
        PostWebhooksSendRequestBodyTypedDict,
        PostWebhooksSendRequestTypedDict,
    )
    from .security import Security, SecurityTypedDict

__all__ = [
    "CustomHeaders",
    "CustomHeadersTypedDict",
    "DeleteEndpointGroupsIDRequest",
    "DeleteEndpointGroupsIDRequestTypedDict",
    "DeleteEndpointsIDRequest",
    "DeleteEndpointsIDRequestTypedDict",
    "DeleteEventTypesIDRequest",
    "DeleteEventTypesIDRequestTypedDict",
    "GetEndpointsRequest",
    "GetEndpointsRequestTypedDict",
    "PatchEndpointGroupsIDRequest",
    "PatchEndpointGroupsIDRequestTypedDict",
    "PatchEndpointsIDRequest",
    "PatchEndpointsIDRequestTypedDict",
    "PatchEventTypesIDRequest",
    "PatchEventTypesIDRequestBody",
    "PatchEventTypesIDRequestBodyTypedDict",
    "PatchEventTypesIDRequestTypedDict",
    "PatchEventTypesIDSchema",
    "PatchEventTypesIDSchemaTypedDict",
    "Payload",
    "PayloadTypedDict",
    "PostEndpointGroupsRequest",
    "PostEndpointGroupsRequestTypedDict",
    "PostEndpointsRequest",
    "PostEndpointsRequestTypedDict",
    "PostEventTypesRequest",
    "PostEventTypesRequestTypedDict",
    "PostEventTypesSchema",
    "PostEventTypesSchemaTypedDict",
    "PostWebhooksSendRequest",
    "PostWebhooksSendRequestBody",
    "PostWebhooksSendRequestBodyTypedDict",
    "PostWebhooksSendRequestTypedDict",
    "RetryPolicy",
    "Security",
    "SecurityTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "DeleteEndpointGroupsIDRequest": ".delete_endpoint_groups_id_op",
    "DeleteEndpointGroupsIDRequestTypedDict": ".delete_endpoint_groups_id_op",
    "DeleteEndpointsIDRequest": ".delete_endpoints_id_op",
    "DeleteEndpointsIDRequestTypedDict": ".delete_endpoints_id_op",
    "DeleteEventTypesIDRequest": ".delete_event_types_id_op",
    "DeleteEventTypesIDRequestTypedDict": ".delete_event_types_id_op",
    "GetEndpointsRequest": ".get_endpointsop",
    "GetEndpointsRequestTypedDict": ".get_endpointsop",
    "PatchEndpointGroupsIDRequest": ".patch_endpoint_groups_id_op",
    "PatchEndpointGroupsIDRequestTypedDict": ".patch_endpoint_groups_id_op",
    "PatchEndpointsIDRequest": ".patch_endpoints_id_op",
    "PatchEndpointsIDRequestTypedDict": ".patch_endpoints_id_op",
    "PatchEventTypesIDRequest": ".patch_event_types_id_op",
    "PatchEventTypesIDRequestBody": ".patch_event_types_id_op",
    "PatchEventTypesIDRequestBodyTypedDict": ".patch_event_types_id_op",
    "PatchEventTypesIDRequestTypedDict": ".patch_event_types_id_op",
    "PatchEventTypesIDSchema": ".patch_event_types_id_op",
    "PatchEventTypesIDSchemaTypedDict": ".patch_event_types_id_op",
    "PostEndpointGroupsRequest": ".post_endpoint_groupsop",
    "PostEndpointGroupsRequestTypedDict": ".post_endpoint_groupsop",
    "CustomHeaders": ".post_endpointsop",
    "CustomHeadersTypedDict": ".post_endpointsop",
    "PostEndpointsRequest": ".post_endpointsop",
    "PostEndpointsRequestTypedDict": ".post_endpointsop",
    "RetryPolicy": ".post_endpointsop",
    "PostEventTypesRequest": ".post_event_typesop",
    "PostEventTypesRequestTypedDict": ".post_event_typesop",
    "PostEventTypesSchema": ".post_event_typesop",
    "PostEventTypesSchemaTypedDict": ".post_event_typesop",
    "Payload": ".post_webhooks_sendop",
    "PayloadTypedDict": ".post_webhooks_sendop",
    "PostWebhooksSendRequest": ".post_webhooks_sendop",
    "PostWebhooksSendRequestBody": ".post_webhooks_sendop",
    "PostWebhooksSendRequestBodyTypedDict": ".post_webhooks_sendop",
    "PostWebhooksSendRequestTypedDict": ".post_webhooks_sendop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
