"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
from hookhq.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEndpointsRequestTypedDict(TypedDict):
    enabled: NotRequired[bool]
    r"""Whether to filter endpoints by enabled status"""


class GetEndpointsRequest(BaseModel):
    enabled: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Whether to filter endpoints by enabled status"""
