"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
from hookhq.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchEventTypesIDSchemaTypedDict(TypedDict):
    r"""Event type schema"""


class PatchEventTypesIDSchema(BaseModel):
    r"""Event type schema"""


class PatchEventTypesIDRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Event type name"""
    description: NotRequired[str]
    r"""Event type description"""
    schema_: NotRequired[PatchEventTypesIDSchemaTypedDict]
    r"""Event type schema"""
    enabled: NotRequired[bool]
    r"""Event type enabled status"""


class PatchEventTypesIDRequestBody(BaseModel):
    name: Optional[str] = None
    r"""Event type name"""

    description: Optional[str] = None
    r"""Event type description"""

    schema_: Annotated[
        Optional[PatchEventTypesIDSchema], pydantic.Field(alias="schema")
    ] = None
    r"""Event type schema"""

    enabled: Optional[bool] = None
    r"""Event type enabled status"""


class PatchEventTypesIDRequestTypedDict(TypedDict):
    id: str
    r"""Event type ID"""
    request_body: PatchEventTypesIDRequestBodyTypedDict


class PatchEventTypesIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Event type ID"""

    request_body: Annotated[
        PatchEventTypesIDRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
