"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostEndpointGroupsRequestTypedDict(TypedDict):
    name: str
    r"""Name of the endpoint group"""
    description: NotRequired[str]
    r"""Description of the endpoint group"""
    endpoint_ids: NotRequired[List[str]]
    r"""List of endpoint IDs"""
    enabled: NotRequired[bool]
    r"""Whether the endpoint group is enabled"""


class PostEndpointGroupsRequest(BaseModel):
    name: str
    r"""Name of the endpoint group"""

    description: Optional[str] = None
    r"""Description of the endpoint group"""

    endpoint_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="endpointIds")
    ] = None
    r"""List of endpoint IDs"""

    enabled: Optional[bool] = None
    r"""Whether the endpoint group is enabled"""
