"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
from hookhq.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PayloadTypedDict(TypedDict):
    r"""Payload to send with the webhook"""


class Payload(BaseModel):
    r"""Payload to send with the webhook"""


class PostWebhooksSendRequestBodyTypedDict(TypedDict):
    endpoints: List[str]
    r"""List of endpoints or endpoint groups to send the webhook to"""
    payload: PayloadTypedDict
    r"""Payload to send with the webhook"""
    event_type: NotRequired[str]
    r"""Event type to send the webhook to. Required if sending to an endpoint group."""
    event_id: NotRequired[str]
    r"""Optional unique event ID to track the webhook"""


class PostWebhooksSendRequestBody(BaseModel):
    endpoints: List[str]
    r"""List of endpoints or endpoint groups to send the webhook to"""

    payload: Payload
    r"""Payload to send with the webhook"""

    event_type: Annotated[Optional[str], pydantic.Field(alias="eventType")] = None
    r"""Event type to send the webhook to. Required if sending to an endpoint group."""

    event_id: Annotated[Optional[str], pydantic.Field(alias="eventId")] = None
    r"""Optional unique event ID to track the webhook"""


class PostWebhooksSendRequestTypedDict(TypedDict):
    idempotency_key: NotRequired[str]
    r"""Optional idempotency key"""
    request_body: NotRequired[PostWebhooksSendRequestBodyTypedDict]


class PostWebhooksSendRequest(BaseModel):
    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Optional idempotency key"""

    request_body: Annotated[
        Optional[PostWebhooksSendRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
