"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostEventTypesSchemaTypedDict(TypedDict):
    r"""JSON Schema for event payload validation (must be valid JSON Schema)"""


class PostEventTypesSchema(BaseModel):
    r"""JSON Schema for event payload validation (must be valid JSON Schema)"""


class PostEventTypesRequestTypedDict(TypedDict):
    name: str
    r"""Name of the event type"""
    description: NotRequired[str]
    r"""Description of the event type"""
    schema_: NotRequired[PostEventTypesSchemaTypedDict]
    r"""JSON Schema for event payload validation (must be valid JSON Schema)"""
    enabled: NotRequired[bool]
    r"""Whether the event type is enabled"""


class PostEventTypesRequest(BaseModel):
    name: str
    r"""Name of the event type"""

    description: Optional[str] = None
    r"""Description of the event type"""

    schema_: Annotated[
        Optional[PostEventTypesSchema], pydantic.Field(alias="schema")
    ] = None
    r"""JSON Schema for event payload validation (must be valid JSON Schema)"""

    enabled: Optional[bool] = None
    r"""Whether the event type is enabled"""
