"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from hookhq.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


RetryPolicy = Literal[
    "exponential",
    "linear",
    "fixed",
]
r"""Retry policy of the endpoint"""


class CustomHeadersTypedDict(TypedDict):
    r"""Custom headers of the endpoint"""


class CustomHeaders(BaseModel):
    r"""Custom headers of the endpoint"""


class PostEndpointsRequestTypedDict(TypedDict):
    name: str
    r"""Name of the endpoint"""
    url: str
    r"""URL of the endpoint"""
    description: NotRequired[str]
    r"""Description of the endpoint"""
    enabled: NotRequired[bool]
    r"""Whether the endpoint is enabled"""
    retry_policy: NotRequired[RetryPolicy]
    r"""Retry policy of the endpoint"""
    max_attempts: NotRequired[float]
    r"""Maximum number of attempts of the endpoint"""
    timeout_ms: NotRequired[float]
    r"""Timeout of the endpoint"""
    custom_headers: NotRequired[CustomHeadersTypedDict]
    r"""Custom headers of the endpoint"""
    proxy_group_id: NotRequired[str]
    r"""Proxy group ID of the endpoint"""


class PostEndpointsRequest(BaseModel):
    name: str
    r"""Name of the endpoint"""

    url: str
    r"""URL of the endpoint"""

    description: Optional[str] = None
    r"""Description of the endpoint"""

    enabled: Optional[bool] = True
    r"""Whether the endpoint is enabled"""

    retry_policy: Annotated[
        Optional[RetryPolicy], pydantic.Field(alias="retryPolicy")
    ] = "exponential"
    r"""Retry policy of the endpoint"""

    max_attempts: Annotated[Optional[float], pydantic.Field(alias="maxAttempts")] = 3
    r"""Maximum number of attempts of the endpoint"""

    timeout_ms: Annotated[Optional[float], pydantic.Field(alias="timeoutMs")] = 30000
    r"""Timeout of the endpoint"""

    custom_headers: Annotated[
        Optional[CustomHeaders], pydantic.Field(alias="customHeaders")
    ] = None
    r"""Custom headers of the endpoint"""

    proxy_group_id: Annotated[Optional[str], pydantic.Field(alias="proxyGroupId")] = (
        None
    )
    r"""Proxy group ID of the endpoint"""
