/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HookHQError } from "./hookhqerror.js";

/**
 * Internal server error
 */
export type PostApiPortalTokenInternalServerErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class PostApiPortalTokenInternalServerError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiPortalTokenInternalServerErrorData;

  constructor(
    err: PostApiPortalTokenInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiPortalTokenInternalServerError";
  }
}

/**
 * Rate limit exceeded
 */
export type PostApiPortalTokenTooManyRequestsErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Rate limit exceeded
 */
export class PostApiPortalTokenTooManyRequestsError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiPortalTokenTooManyRequestsErrorData;

  constructor(
    err: PostApiPortalTokenTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiPortalTokenTooManyRequestsError";
  }
}

/**
 * Endpoint group not found
 */
export type NotFoundErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Endpoint group not found
 */
export class NotFoundError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "NotFoundError";
  }
}

/**
 * Forbidden
 */
export type PostApiPortalTokenForbiddenErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Forbidden
 */
export class PostApiPortalTokenForbiddenError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiPortalTokenForbiddenErrorData;

  constructor(
    err: PostApiPortalTokenForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiPortalTokenForbiddenError";
  }
}

/**
 * Unauthorized
 */
export type PostApiPortalTokenUnauthorizedErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Unauthorized
 */
export class PostApiPortalTokenUnauthorizedError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiPortalTokenUnauthorizedErrorData;

  constructor(
    err: PostApiPortalTokenUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiPortalTokenUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type PostApiPortalTokenBadRequestErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class PostApiPortalTokenBadRequestError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiPortalTokenBadRequestErrorData;

  constructor(
    err: PostApiPortalTokenBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiPortalTokenBadRequestError";
  }
}

/** @internal */
export const PostApiPortalTokenInternalServerError$inboundSchema: z.ZodType<
  PostApiPortalTokenInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiPortalTokenInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiPortalTokenInternalServerError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenInternalServerError$outboundSchema: z.ZodType<
  PostApiPortalTokenInternalServerError$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenInternalServerError
> = z.instanceof(PostApiPortalTokenInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenInternalServerError$ {
  /** @deprecated use `PostApiPortalTokenInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    PostApiPortalTokenInternalServerError$inboundSchema;
  /** @deprecated use `PostApiPortalTokenInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    PostApiPortalTokenInternalServerError$outboundSchema;
  /** @deprecated use `PostApiPortalTokenInternalServerError$Outbound` instead. */
  export type Outbound = PostApiPortalTokenInternalServerError$Outbound;
}

/** @internal */
export const PostApiPortalTokenTooManyRequestsError$inboundSchema: z.ZodType<
  PostApiPortalTokenTooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiPortalTokenTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiPortalTokenTooManyRequestsError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenTooManyRequestsError$outboundSchema: z.ZodType<
  PostApiPortalTokenTooManyRequestsError$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenTooManyRequestsError
> = z.instanceof(PostApiPortalTokenTooManyRequestsError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenTooManyRequestsError$ {
  /** @deprecated use `PostApiPortalTokenTooManyRequestsError$inboundSchema` instead. */
  export const inboundSchema =
    PostApiPortalTokenTooManyRequestsError$inboundSchema;
  /** @deprecated use `PostApiPortalTokenTooManyRequestsError$outboundSchema` instead. */
  export const outboundSchema =
    PostApiPortalTokenTooManyRequestsError$outboundSchema;
  /** @deprecated use `PostApiPortalTokenTooManyRequestsError$Outbound` instead. */
  export type Outbound = PostApiPortalTokenTooManyRequestsError$Outbound;
}

/** @internal */
export const NotFoundError$inboundSchema: z.ZodType<
  NotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type NotFoundError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const NotFoundError$outboundSchema: z.ZodType<
  NotFoundError$Outbound,
  z.ZodTypeDef,
  NotFoundError
> = z.instanceof(NotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotFoundError$ {
  /** @deprecated use `NotFoundError$inboundSchema` instead. */
  export const inboundSchema = NotFoundError$inboundSchema;
  /** @deprecated use `NotFoundError$outboundSchema` instead. */
  export const outboundSchema = NotFoundError$outboundSchema;
  /** @deprecated use `NotFoundError$Outbound` instead. */
  export type Outbound = NotFoundError$Outbound;
}

/** @internal */
export const PostApiPortalTokenForbiddenError$inboundSchema: z.ZodType<
  PostApiPortalTokenForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiPortalTokenForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiPortalTokenForbiddenError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenForbiddenError$outboundSchema: z.ZodType<
  PostApiPortalTokenForbiddenError$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenForbiddenError
> = z.instanceof(PostApiPortalTokenForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenForbiddenError$ {
  /** @deprecated use `PostApiPortalTokenForbiddenError$inboundSchema` instead. */
  export const inboundSchema = PostApiPortalTokenForbiddenError$inboundSchema;
  /** @deprecated use `PostApiPortalTokenForbiddenError$outboundSchema` instead. */
  export const outboundSchema = PostApiPortalTokenForbiddenError$outboundSchema;
  /** @deprecated use `PostApiPortalTokenForbiddenError$Outbound` instead. */
  export type Outbound = PostApiPortalTokenForbiddenError$Outbound;
}

/** @internal */
export const PostApiPortalTokenUnauthorizedError$inboundSchema: z.ZodType<
  PostApiPortalTokenUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiPortalTokenUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiPortalTokenUnauthorizedError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenUnauthorizedError$outboundSchema: z.ZodType<
  PostApiPortalTokenUnauthorizedError$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenUnauthorizedError
> = z.instanceof(PostApiPortalTokenUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenUnauthorizedError$ {
  /** @deprecated use `PostApiPortalTokenUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    PostApiPortalTokenUnauthorizedError$inboundSchema;
  /** @deprecated use `PostApiPortalTokenUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    PostApiPortalTokenUnauthorizedError$outboundSchema;
  /** @deprecated use `PostApiPortalTokenUnauthorizedError$Outbound` instead. */
  export type Outbound = PostApiPortalTokenUnauthorizedError$Outbound;
}

/** @internal */
export const PostApiPortalTokenBadRequestError$inboundSchema: z.ZodType<
  PostApiPortalTokenBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiPortalTokenBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiPortalTokenBadRequestError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostApiPortalTokenBadRequestError$outboundSchema: z.ZodType<
  PostApiPortalTokenBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiPortalTokenBadRequestError
> = z.instanceof(PostApiPortalTokenBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiPortalTokenBadRequestError$ {
  /** @deprecated use `PostApiPortalTokenBadRequestError$inboundSchema` instead. */
  export const inboundSchema = PostApiPortalTokenBadRequestError$inboundSchema;
  /** @deprecated use `PostApiPortalTokenBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    PostApiPortalTokenBadRequestError$outboundSchema;
  /** @deprecated use `PostApiPortalTokenBadRequestError$Outbound` instead. */
  export type Outbound = PostApiPortalTokenBadRequestError$Outbound;
}
