/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HookHQError } from "./hookhqerror.js";

/**
 * Internal server error
 */
export type PostWebhooksSendInternalServerErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class PostWebhooksSendInternalServerError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostWebhooksSendInternalServerErrorData;

  constructor(
    err: PostWebhooksSendInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostWebhooksSendInternalServerError";
  }
}

/**
 * Rate limit exceeded
 */
export type PostWebhooksSendTooManyRequestsErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Rate limit exceeded
 */
export class PostWebhooksSendTooManyRequestsError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostWebhooksSendTooManyRequestsErrorData;

  constructor(
    err: PostWebhooksSendTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostWebhooksSendTooManyRequestsError";
  }
}

/**
 * Forbidden
 */
export type PostWebhooksSendForbiddenErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Forbidden
 */
export class PostWebhooksSendForbiddenError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostWebhooksSendForbiddenErrorData;

  constructor(
    err: PostWebhooksSendForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostWebhooksSendForbiddenError";
  }
}

/**
 * Unauthorized
 */
export type PostWebhooksSendUnauthorizedErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Unauthorized
 */
export class PostWebhooksSendUnauthorizedError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostWebhooksSendUnauthorizedErrorData;

  constructor(
    err: PostWebhooksSendUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostWebhooksSendUnauthorizedError";
  }
}

/**
 * Bad request (invalid payload, missing required fields, or payload validation failed)
 */
export type PostWebhooksSendBadRequestErrorData = {
  /**
   * Error message
   */
  error?: string | undefined;
};

/**
 * Bad request (invalid payload, missing required fields, or payload validation failed)
 */
export class PostWebhooksSendBadRequestError extends HookHQError {
  /**
   * Error message
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostWebhooksSendBadRequestErrorData;

  constructor(
    err: PostWebhooksSendBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostWebhooksSendBadRequestError";
  }
}

/** @internal */
export const PostWebhooksSendInternalServerError$inboundSchema: z.ZodType<
  PostWebhooksSendInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostWebhooksSendInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostWebhooksSendInternalServerError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostWebhooksSendInternalServerError$outboundSchema: z.ZodType<
  PostWebhooksSendInternalServerError$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendInternalServerError
> = z.instanceof(PostWebhooksSendInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendInternalServerError$ {
  /** @deprecated use `PostWebhooksSendInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    PostWebhooksSendInternalServerError$inboundSchema;
  /** @deprecated use `PostWebhooksSendInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    PostWebhooksSendInternalServerError$outboundSchema;
  /** @deprecated use `PostWebhooksSendInternalServerError$Outbound` instead. */
  export type Outbound = PostWebhooksSendInternalServerError$Outbound;
}

/** @internal */
export const PostWebhooksSendTooManyRequestsError$inboundSchema: z.ZodType<
  PostWebhooksSendTooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostWebhooksSendTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostWebhooksSendTooManyRequestsError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostWebhooksSendTooManyRequestsError$outboundSchema: z.ZodType<
  PostWebhooksSendTooManyRequestsError$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendTooManyRequestsError
> = z.instanceof(PostWebhooksSendTooManyRequestsError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendTooManyRequestsError$ {
  /** @deprecated use `PostWebhooksSendTooManyRequestsError$inboundSchema` instead. */
  export const inboundSchema =
    PostWebhooksSendTooManyRequestsError$inboundSchema;
  /** @deprecated use `PostWebhooksSendTooManyRequestsError$outboundSchema` instead. */
  export const outboundSchema =
    PostWebhooksSendTooManyRequestsError$outboundSchema;
  /** @deprecated use `PostWebhooksSendTooManyRequestsError$Outbound` instead. */
  export type Outbound = PostWebhooksSendTooManyRequestsError$Outbound;
}

/** @internal */
export const PostWebhooksSendForbiddenError$inboundSchema: z.ZodType<
  PostWebhooksSendForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostWebhooksSendForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostWebhooksSendForbiddenError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostWebhooksSendForbiddenError$outboundSchema: z.ZodType<
  PostWebhooksSendForbiddenError$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendForbiddenError
> = z.instanceof(PostWebhooksSendForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendForbiddenError$ {
  /** @deprecated use `PostWebhooksSendForbiddenError$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendForbiddenError$inboundSchema;
  /** @deprecated use `PostWebhooksSendForbiddenError$outboundSchema` instead. */
  export const outboundSchema = PostWebhooksSendForbiddenError$outboundSchema;
  /** @deprecated use `PostWebhooksSendForbiddenError$Outbound` instead. */
  export type Outbound = PostWebhooksSendForbiddenError$Outbound;
}

/** @internal */
export const PostWebhooksSendUnauthorizedError$inboundSchema: z.ZodType<
  PostWebhooksSendUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostWebhooksSendUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostWebhooksSendUnauthorizedError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostWebhooksSendUnauthorizedError$outboundSchema: z.ZodType<
  PostWebhooksSendUnauthorizedError$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendUnauthorizedError
> = z.instanceof(PostWebhooksSendUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendUnauthorizedError$ {
  /** @deprecated use `PostWebhooksSendUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendUnauthorizedError$inboundSchema;
  /** @deprecated use `PostWebhooksSendUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    PostWebhooksSendUnauthorizedError$outboundSchema;
  /** @deprecated use `PostWebhooksSendUnauthorizedError$Outbound` instead. */
  export type Outbound = PostWebhooksSendUnauthorizedError$Outbound;
}

/** @internal */
export const PostWebhooksSendBadRequestError$inboundSchema: z.ZodType<
  PostWebhooksSendBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostWebhooksSendBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostWebhooksSendBadRequestError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PostWebhooksSendBadRequestError$outboundSchema: z.ZodType<
  PostWebhooksSendBadRequestError$Outbound,
  z.ZodTypeDef,
  PostWebhooksSendBadRequestError
> = z.instanceof(PostWebhooksSendBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostWebhooksSendBadRequestError$ {
  /** @deprecated use `PostWebhooksSendBadRequestError$inboundSchema` instead. */
  export const inboundSchema = PostWebhooksSendBadRequestError$inboundSchema;
  /** @deprecated use `PostWebhooksSendBadRequestError$outboundSchema` instead. */
  export const outboundSchema = PostWebhooksSendBadRequestError$outboundSchema;
  /** @deprecated use `PostWebhooksSendBadRequestError$Outbound` instead. */
  export type Outbound = PostWebhooksSendBadRequestError$Outbound;
}
