/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { HookHQCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { HookHQError } from "../models/errors/hookhqerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Send a webhook to the specified endpoints.
 *
 *  Webhooks can be sent to endpoints and/or endpoint groups.
 *  In order to send a webhook to an endpoint group, the eventType must be specified, then the webhook will be dispatched to all endpoints in the group that are subscribed to the eventType.
 */
export function webhooksSend(
  client: HookHQCore,
  request?: operations.PostWebhooksSendRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.PostWebhooksSendResponse,
    | errors.PostWebhooksSendBadRequestError
    | errors.PostWebhooksSendUnauthorizedError
    | errors.PostWebhooksSendForbiddenError
    | errors.PostWebhooksSendTooManyRequestsError
    | errors.PostWebhooksSendInternalServerError
    | HookHQError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: HookHQCore,
  request?: operations.PostWebhooksSendRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.PostWebhooksSendResponse,
      | errors.PostWebhooksSendBadRequestError
      | errors.PostWebhooksSendUnauthorizedError
      | errors.PostWebhooksSendForbiddenError
      | errors.PostWebhooksSendTooManyRequestsError
      | errors.PostWebhooksSendInternalServerError
      | HookHQError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      operations.PostWebhooksSendRequest$outboundSchema.optional().parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload?.RequestBody, { explode: true });

  const path = pathToFunc("/webhooks/send")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
    "Idempotency-Key": encodeSimple(
      "Idempotency-Key",
      payload?.["Idempotency-Key"],
      { explode: false, charEncoding: "none" },
    ),
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "post_/webhooks/send",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || {
        strategy: "backoff",
        backoff: {
          initialInterval: 500,
          maxInterval: 60000,
          exponent: 1.5,
          maxElapsedTime: 3600000,
        },
        retryConnectionErrors: true,
      }
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["5XX"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "401", "403", "429", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.PostWebhooksSendResponse,
    | errors.PostWebhooksSendBadRequestError
    | errors.PostWebhooksSendUnauthorizedError
    | errors.PostWebhooksSendForbiddenError
    | errors.PostWebhooksSendTooManyRequestsError
    | errors.PostWebhooksSendInternalServerError
    | HookHQError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.PostWebhooksSendResponse$inboundSchema),
    M.jsonErr(400, errors.PostWebhooksSendBadRequestError$inboundSchema),
    M.jsonErr(401, errors.PostWebhooksSendUnauthorizedError$inboundSchema),
    M.jsonErr(403, errors.PostWebhooksSendForbiddenError$inboundSchema),
    M.jsonErr(429, errors.PostWebhooksSendTooManyRequestsError$inboundSchema),
    M.jsonErr(500, errors.PostWebhooksSendInternalServerError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
